"""Resolve a ParentVUE-reported school name to that school's own website.

The bundled ``mcps_schools.json`` (regenerated by ``scripts/refresh_schools.py``)
is the source of truth. Resolution happens at *render* time — there is no DB
column — so the mapping is always whatever ships with the installed code, and a
miss degrades silently to plain text.

The portal reports a school name in whatever form Synergy holds ("Bethesda-Chevy
Chase HS", "Winston Churchill High School", …), while the directory stores a
long index name ("Winston Churchill") and an abbreviated short name ("Winston
Churchill HS"). To bridge that, every name is normalized *and* its trailing
level word is canonicalized — "HS", "High", "High School" all fold to one token
— so "Poolesville High School" (portal) and "Poolesville HS" (directory) land on
the same key.

Matching is then two-tier:

* ``full``  — the whole canonical name, level word kept. An exact hit wins.
* ``loose`` — the same name with its trailing level word removed, used only for
  schools that carried one (bridges a bare portal name against a level-suffixed
  directory entry).

Both maps drop any key that two different schools would claim, so an ambiguous
name (a bare "Poolesville", which is an ES *and* an HS) resolves to nothing
rather than the wrong school. Both the directory's index name and its overview
short name are indexed, covering the long/short gap from either side.
"""
from __future__ import annotations

import json
import re
import unicodedata
from functools import lru_cache
from pathlib import Path
from typing import Optional

_DATA_PATH = Path(__file__).with_name("mcps_schools.json")

# Trailing level markers → one canonical token. Each group's variants (incl. the
# bare "high"/"middle"/"elementary" and the "hs"/"ms"/"es" abbreviations) all
# fold to the same string, so long and short spellings produce one key.
_LEVEL_CANON = (
    (("high school", "high", "hs"), "high school"),
    (("middle school", "middle", "ms"), "middle school"),
    (("elementary school", "elementary", "elem", "es"), "elementary school"),
)
_CANON_TOKENS = tuple(canon for _, canon in _LEVEL_CANON)

# Manual overrides for portal spellings that won't normalize to the directory's
# form. Keys and values are both already-normalized (see ``_normalize``).
# Populate only when a real mismatch turns up; empty is the healthy state.
_ALIASES: dict[str, str] = {}

_NONWORD_RE = re.compile(r"[^a-z0-9]+")


def _normalize(name: str) -> str:
    """Casefold, fold accents, ``&`` → ``and``, punctuation → spaces, collapse
    whitespace. Level words survive here; ``_canon`` folds them next."""
    s = unicodedata.normalize("NFKD", name or "").casefold()
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = s.replace("&", " and ")
    s = _NONWORD_RE.sub(" ", s)
    return " ".join(s.split())


def _canon(key: str) -> str:
    """Fold a *trailing* level marker to its canonical token."""
    for variants, canon in _LEVEL_CANON:
        for v in variants:
            if key.endswith(" " + v):
                return key[: -len(v)].rstrip() + " " + canon
    return key


def _base(key: str) -> str:
    """Drop a trailing canonical level token, leaving the bare school name."""
    for canon in _CANON_TOKENS:
        if key.endswith(" " + canon):
            return key[: -len(canon)].rstrip()
    return key


def _key(name: str) -> str:
    """Full lookup key: normalized + level-canonicalized (via aliases)."""
    k = _canon(_normalize(name))
    return _ALIASES.get(k, k)


def _add(target: dict[str, str], ambiguous: set[str], key: str, url: str) -> None:
    if not key:
        return
    if key in target and target[key] != url:
        ambiguous.add(key)          # two schools want this key — trust neither
    target.setdefault(key, url)


@lru_cache(maxsize=1)
def _index() -> tuple[dict[str, str], dict[str, str]]:
    """``(full_key -> url, loose_key -> url)`` from the bundled JSON. Any key two
    different URLs would claim is dropped. Missing/invalid file yields empty maps
    so every lookup returns None."""
    try:
        data = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}, {}

    full: dict[str, str] = {}
    loose: dict[str, str] = {}
    full_amb: set[str] = set()
    loose_amb: set[str] = set()
    for rec in data.get("schools", ()):
        url = rec.get("website") or rec.get("overview_url")
        if not url:
            continue
        for raw in {rec.get("name", ""), rec.get("short_name", "")}:
            fk = _key(raw)
            _add(full, full_amb, fk, url)
            base = _base(fk)
            if base != fk:                  # only names that carried a level
                _add(loose, loose_amb, base, url)
    for k in full_amb:
        full.pop(k, None)
    for k in loose_amb:
        loose.pop(k, None)
    return full, loose


def school_url(name: str) -> Optional[str]:
    """The school's own website (or the MCPS overview page as a fallback) for a
    ParentVUE school name; ``None`` when unknown, ambiguous, or empty."""
    key = _key(name)
    if not key:
        return None
    full, loose = _index()
    if key in full:                    # exact, level-qualified match wins
        return full[key]
    return loose.get(_base(key))       # bare-vs-suffixed gap, only if unambiguous
